import glob
import os

#singularity: "docker://poquirion/ncov-tools:latest"
singularity: "/home/poq/covid/package_ncov-tools/.snakemake/singularity/7f0a6cf10df7320052c57c5468fcf292.simg"

include: "rules/common.smk"
include: "rules/sequencing.smk"
include: "rules/analysis.smk"
include: "rules/annotation.smk"
include: "rules/report.smk"

rule all:
    input:
        get_qc_sequencing_plots,
        get_qc_analysis_plots,
        get_qc_reports
