name: ncov-qc
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake
  - mafft
  - augur
  - pysam
  - r-base
  - iqtree
  - bioconductor-ggtree
  - r-argparse
  - r-patchwork
  - r-ggforce
  - bedtools
  - samtools
  - parasail-python
  - newick_utils
  - pip=19.3.1
  - minimap2
  - poppler
  - gofasta
  - numpy
  - biopython
  - snpeff=5.0-0
  - icu
  - boost-cpp
  - usher
  - setuptools=81.0.0
  - pangolin
  - pip:
      - dendropy>=4.4.0
      - pyvcf3
      - ncov-parser
      - git+https://github.com/cov-lineages/constellations.git
      - git+https://github.com/cov-lineages/scorpio.git
      - git+https://github.com/jts/ncov-watch.git
